### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by Glatrix** [LelouBil/PhasBypass#1]
never been able to get melon loader with re-build assembly gen to work... it says "Collecting from unknown thread"
and then the next time i run it says Unable to read vr path. Please Help!
im using Extreme injector and auto-injecting acbypass.
![Capture](https://user-images.githubusercontent.com/73367967/102947478-0f219700-4489-11eb-9c2d-adb210846b36.PNG)

**Comment by LelouBil** [comment]
So you're trying to run the game in VR ?

**Comment by Glatrix** [comment]
No, i fixed it though. Are you making a new bypass for the update? I'm really mad that an update came out just as i finally got hacks to work that were not made me. If you need any help testing ac let me know!

**Comment by LelouBil** [comment]
It is updated already
