### ISSUE TITLE
Bypass works but wit a flaw.

### ISSUE THREAD

**Issue by IamN4m3l3ss** [LelouBil/PhasBypass#2]
I probably did something wrong when building it but heres the deal. Injecting the bypass when the MelonLoader console is loading (i was using the auto inject settings wit a 2000 delay) it gives an error saying: "Collecting data from unknown GC" (or something similar to that) and it wont boot the game. But when manualy injecting it before the Unity logo dissapears it works fine (and so do the mods) again i probably did something wrong when building it. But could you maybe give me some instructions on how to do it properly the next time? Thank you in advance. (Please excuse my bad english.)

**Comment by LelouBil** [comment]
Are you sure you didn't have a MelonLoader mod that could cause this popup ?

**Comment by IamN4m3l3ss** [comment]
Nope. It are the exact same mods i used yesterday (before the update). And it also only appears when i inject the bypass while the MelonLoader console is still loading (without the game being opened yet). And once again, i probably just did something wrong when building the thing. (Oh also the console closes then the popup appears and then silence, ill look through the logs and try to figure out whats wrong.)

**Comment by Glatrix** [comment]
Same here, I think we need a new bypass.

**Comment by IamN4m3l3ss** [comment]
Tried looking through the logs. And it appears that the OwO universal MelonLoader mod.... well..... Lets say we need to hire a furry to translate the logs... Anyways i figured out the problem. https://seriously.go-outsi.de/zyIef8 (screenshot) basicly if the bypass hooks before it showing the game info/mods etc it will end up giving you that error. If it injects after the game/mod info showed up it will work fine.
