### ISSUE TITLE
Not connecting to steam

### ISSUE THREAD

**Issue by Ronniedafox** [LelouBil/PhasBypass#4]
I have done everything right and it shows this 
![Phasmophobia 25_03_2021 18_29_32](https://user-images.githubusercontent.com/68481275/112525051-65f48080-8d98-11eb-94d7-e39b15c85ab7.png)

**Comment by juaneth** [comment]
pooey

**Comment by LelouBil** [comment]
You launched the game directly with the executable file, you need to launch it via steam/a steam shortcut to have it connect to steam.
